### ISSUE TITLE
No carousel, no header

### ISSUE THREAD

**Issue by MorganLee909** [ivanko22/Studytube-Schedule#2]
The carousel is not appearing at all.  Also the header image no longer appears.  Tried on three different browsers:  Firefox, Brave, Chromium.

**Comment by ivanko22** [comment]
Thanks, will check it shortly.

**Comment by ivanko22** [comment]
@MorganLee909 There are was wronge link reference and also I forgot to upload JS files. Now it should work.

**Comment by MorganLee909** [comment]
Great.  Working good now.  I will work on backend.
